Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 4

Metrics/LineLength:
  Max: 120

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  MaxSlashes: 0

Style/DeprecatedHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

