Lint/UselessAssignment:
  Enabled: true

# Offense count: 3
Metrics/AbcSize:
  Max: 24

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 104

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 7

# Offense count: 48
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# Offense count: 2
Style/AccessorMethodName:
  Enabled: false

# Cop supports --auto-correct.
Style/AlignArray:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: true

# Cop supports --auto-correct.
Style/BlockEndNewline:
  Enabled: true

# Cop supports --auto-correct.
Style/Blocks:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: true

# Offense count: 1
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: true

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Enabled: false

# Offense count: 17
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/EachWithObject:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Offense count: 24
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: true

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: false

# Offense count: 3
# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 3
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 5
# Configuration parameters: SupportedStyles.
Style/RaiseArgs:
  EnforcedStyle: compact

# Offense count: 2
Style/RegexpLiteral:
  MaxSlashes: 0

# Offense count: 1
Style/RescueModifier:
  Enabled: false

# Offense count: 17
# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceAfterSemicolon:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 20
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 124
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 7
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: false
