---
http_interactions:
- request:
    method: post
    uri: http://api.uat.sulserver.net/applicants/add
    body:
      encoding: UTF-8
      string: '{"applicants":[{"journeystatus":1,"manadd":1,"firstname":"clive brian","surname":"shirley","dob":"1971-09-14","address1":"Fifty
        Pence Building","address2":"12 Addiscomb Road","citytown":"Croydon","county":"surrey","postcode":"CR2
        0LN","emailaddress":"test_user_2@foobar.com","telephone":"0777888888","gender":"Male","wherehearnew":14,"marketingagree":1,"referral_partner":0,"subdate":"2015-02-13
        14:21:41 +0100"}],"accessKey":"iGy8G5dUmr9HXINAOc7MIG9m1bd8bv8K"}'
    headers:
      User-Agent:
      - startup_loans_ruby_gem 0.0.1
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Fri, 13 Feb 2015 13:21:41 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      Access-Control-Allow-Origin:
      - "*"
      X-Frame-Options:
      - SAMEORIGIN
    body:
      encoding: UTF-8
      string: '{"success":true,"results":{"0":{"appid":"629837"},"successful":1,"failed":0,"total":1}}'
    http_version: 
  recorded_at: Fri, 13 Feb 2015 13:21:41 GMT
recorded_with: VCR 2.9.3
